# Generated by Django 4.1.3 on 2022-11-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_alter_task_options_rename_datetime_task_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["is_completed", "-created_at"]},
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="todo.tag"),
        ),
    ]
